version: '2.3'

services:
  postgres:
    container_name: 'postgres'
    build:
      context: ./infrastructure/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ex_mon_api_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - elixir
    expose:
      - 5432
    ports:
      - 5432:5432

networks:
  elixir:
    driver: bridge